
# 请求中不同查询参数的获取 jsonObj
POST http://localhost:8082/param/jsonObj
Content-Type: application/json

//{"ids": 1, "names": "anson", "hobby": "badminton"}
//{"id": 1, "name": "anson", "hobby": "badminton"}
//{"id": 1, "name": "anson", "age": 12}
{"id": 1, "names": "anson"}

###
