server:
  port: 8084

spring:
  #数据源
  datasource:
    url: jdbc:mysql://10.10.4.36:3306/wf_carinfo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dataaccess
    password: da123qwe
