server:
  port: 8082

spring:
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.10.4.171:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dataaccess
    password: da123qwe
    #连接池的配置信息
    druid:
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,log4j,config
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 1
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  mapper-locations: classpath:com/company/**/mapper/*.xml
  #  type-aliases-package: com.seemmo.airecheck
  configuration:
    map-underscore-to-camel-case: true  #ORM映射是否默认下划线转小驼峰
    return-instance-for-empty-row: false  #列表查询是否返回空对象
    #default-enum-type-handler: com.ycw.medicine.mybatis.handler.IntegerValueEnumTypeHandler #默认枚举处理器